[package]
name = "trader-calculator-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.8"
rusqlite = { version = "0.32", features = ["bundled"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"

[build-dependencies]
slint-build = "1.8"
