// 股票开仓数据
export struct OpenStockData {
    stock_name: string,
    stock_type: int,      // 1-沪市, 2-深市
    current_price:float, // 当前价格
    transaction_price:float, // 交易价格
    transaction_amount:float, // 交易数量
}

// 股票数据结构
export struct StockItem {
    stock_id: int,
    stock_name: string,
    stock_type: int,
    commission_fee_rate: float,
    created_at: string,
}

// 股票操作记录数据结构
export struct StockActionItem {
    stock_action_id: int,
    stock_id: int,
    current_price: float,
    current_cost: float,
    total_amount: float,
    transaction_price: float,
    transaction_amount: float,
    transaction_commission_fee: float,
    action: int,  // 1-建仓 2-平仓 3-加仓 4-减仓
    profit: float,
    profit_rate: float,
    created_at: string,
}
