
import { Button, VerticalBox, HorizontalBox, ListView, LineEdit } from "std-widgets.slint";
component MainHeader {
    height: 50px;
    callback create_stock();
    Rectangle {
        background: white;
    }

    HorizontalBox {
        padding: 10px;
        Rectangle {
            // 左侧占位
        }

        Text {
            text: "交易计算器";
            color: #FE9900;
            font-size: 18px;
            horizontal-alignment: center;
        }

        Rectangle {
            // 右侧占位，推动按钮到最右边
        }

        Rectangle {
            width: 60px;
            height: 30px;
            background: #FE9900;
            border-radius: 4px;
            Text {
                text: "建仓";
                color: white;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            TouchArea {
                clicked => {
                    root.create_stock();
                }
            }
        }
    }
}
